"""Adaptive reliability layer research prototype."""

from .ablation_suite import (
    AblationSuiteResult,
    ablation_suite_to_dict,
    render_ablation_suite_report,
    run_ablation_suite,
)
from .adaptation import (
    AdaptationController,
    AdaptationDecision,
    FrozenPolicy,
    NaiveAdaptationPolicy,
)
from .benchmark_suite import (
    BenchmarkSuiteResult,
    benchmark_suite_to_dict,
    render_benchmark_suite_report,
    run_benchmark_suite,
)
from .environment import build_stream
from .evaluation import (
    BenchmarkResult,
    SimulationResult,
    StepTrace,
    StrategyResult,
    render_benchmark_report,
    run_benchmark,
    run_simulation,
)
from .digits_shift_benchmark import (
    render_digits_shift_benchmark_report,
    run_digits_shift_benchmark,
    run_digits_shift_benchmark_with_factories,
)
from .fashion_mnist_shift_benchmark import (
    FashionBenchmarkConfig,
    render_fashion_mnist_shift_benchmark_report,
    run_fashion_mnist_shift_benchmark,
    run_fashion_mnist_shift_benchmark_with_factories,
)
from .graph_shift_benchmark import (
    GraphBenchmarkResult,
    render_graph_shift_benchmark_report,
    run_graph_shift_benchmark,
)
from .image_scaleup_suite import (
    ImageScaleupSuiteResult,
    image_scaleup_suite_to_dict,
    render_image_scaleup_suite_report,
    run_image_scaleup_suite,
)
from .monitoring import BatchStats, ReferenceProfile, ShiftMonitor, ShiftSignal, build_reference_profile
from .replay.ops_story import run_public_ops_story
from .recurrence_temporal_benchmark import (
    build_recurrence_fashion_mnist_stream,
    recurrence_temporal_benchmark_to_dict,
    render_recurrence_temporal_benchmark_report,
    run_recurrence_temporal_benchmark,
)
from .regime import RegimeDescriptor, StreamingRegimeEncoder, build_regime_embedding
from .risk import MartingaleRiskMonitor, RiskState
from .tabular_benchmark import (
    BanditTabularPolicy,
    DelayedBanditTabularPolicy,
    DelayedHybridBanditSpecialistPolicy,
    FraudContextDelayedBanditTabularPolicy,
    FraudRankDelayedBanditTabularPolicy,
    HybridBanditSpecialistPolicy,
    MultiActionTabularPolicy,
    RegimeAwareDelayedBanditTabularPolicy,
    RoutedDelayedBanditSpecialistPolicy,
    SpecialistMemoryTabularPolicy,
    render_tabular_benchmark_report,
    run_tabular_benchmark,
    run_tabular_benchmark_with_factories,
)
from .temporal_benchmark_suite import (
    TemporalBenchmarkAggregate,
    TemporalBenchmarkSuiteResult,
    TemporalStrategySummary,
    TemporalStrategyAggregate,
    render_temporal_benchmark_suite_report,
    run_temporal_benchmark_suite,
    run_temporal_paper_suite,
    temporal_benchmark_suite_to_dict,
)
from .temporal_fashion_mnist_benchmark import (
    TemporalFashionBenchmarkResult,
    TemporalRewardConfig,
    TemporalFashionStrategyResult,
    render_temporal_fashion_mnist_report,
    run_temporal_fashion_mnist_benchmark,
)
from .torch_model import ModelSnapshot, SourceFitSummary, TorchTabularAdapterModel
from .torch_image_model import TorchImageAdapterModel
from .uncertainty import ReliabilityOutput, UncertaintyWrapper
from .wilds_civilcomments_benchmark import (
    WildsCivilCommentsBenchmarkResult,
    WildsCivilCommentsConfig,
    WildsCivilCommentsSuiteResult,
    WildsBenchmarkAggregate,
    WildsGroupSummary,
    WildsStrategyAggregate,
    WildsStrategySummary,
    render_wilds_civilcomments_report,
    run_wilds_civilcomments_benchmark,
    render_wilds_civilcomments_suite_report,
    run_wilds_civilcomments_suite,
    wilds_civilcomments_benchmark_to_dict,
    wilds_civilcomments_suite_to_dict,
)

__all__ = [
    "AblationSuiteResult",
    "AdaptationController",
    "AdaptationDecision",
    "BatchStats",
    "BanditTabularPolicy",
    "BenchmarkSuiteResult",
    "BenchmarkResult",
    "DelayedBanditTabularPolicy",
    "DelayedHybridBanditSpecialistPolicy",
    "FraudContextDelayedBanditTabularPolicy",
    "FraudRankDelayedBanditTabularPolicy",
    "FrozenPolicy",
    "FashionBenchmarkConfig",
    "GraphBenchmarkResult",
    "HybridBanditSpecialistPolicy",
    "ImageScaleupSuiteResult",
    "MartingaleRiskMonitor",
    "ModelSnapshot",
    "MultiActionTabularPolicy",
    "RegimeAwareDelayedBanditTabularPolicy",
    "RoutedDelayedBanditSpecialistPolicy",
    "RiskState",
    "ReliabilityOutput",
    "ReferenceProfile",
    "RegimeDescriptor",
    "StreamingRegimeEncoder",
    "TemporalRewardConfig",
    "ShiftMonitor",
    "ShiftSignal",
    "SimulationResult",
    "SourceFitSummary",
    "StepTrace",
    "StrategyResult",
    "SpecialistMemoryTabularPolicy",
    "TemporalBenchmarkAggregate",
    "TemporalBenchmarkSuiteResult",
    "TemporalFashionBenchmarkResult",
    "TemporalFashionStrategyResult",
    "TemporalStrategyAggregate",
    "TemporalStrategySummary",
    "TorchImageAdapterModel",
    "TorchTabularAdapterModel",
    "UncertaintyWrapper",
    "WildsCivilCommentsBenchmarkResult",
    "WildsCivilCommentsConfig",
    "WildsCivilCommentsSuiteResult",
    "WildsBenchmarkAggregate",
    "WildsGroupSummary",
    "WildsStrategyAggregate",
    "WildsStrategySummary",
    "ablation_suite_to_dict",
    "benchmark_suite_to_dict",
    "build_stream",
    "build_regime_embedding",
    "build_reference_profile",
    "build_recurrence_fashion_mnist_stream",
    "image_scaleup_suite_to_dict",
    "NaiveAdaptationPolicy",
    "render_benchmark_report",
    "render_ablation_suite_report",
    "render_benchmark_suite_report",
    "render_digits_shift_benchmark_report",
    "render_fashion_mnist_shift_benchmark_report",
    "render_graph_shift_benchmark_report",
    "render_image_scaleup_suite_report",
    "render_recurrence_temporal_benchmark_report",
    "render_tabular_benchmark_report",
    "render_temporal_benchmark_suite_report",
    "render_temporal_fashion_mnist_report",
    "render_wilds_civilcomments_report",
    "render_wilds_civilcomments_suite_report",
    "recurrence_temporal_benchmark_to_dict",
    "run_ablation_suite",
    "run_benchmark",
    "run_benchmark_suite",
    "run_digits_shift_benchmark",
    "run_digits_shift_benchmark_with_factories",
    "run_fashion_mnist_shift_benchmark",
    "run_fashion_mnist_shift_benchmark_with_factories",
    "run_graph_shift_benchmark",
    "run_image_scaleup_suite",
    "run_public_ops_story",
    "run_recurrence_temporal_benchmark",
    "run_tabular_benchmark",
    "run_tabular_benchmark_with_factories",
    "run_temporal_benchmark_suite",
    "run_temporal_fashion_mnist_benchmark",
    "run_temporal_paper_suite",
    "run_simulation",
    "run_wilds_civilcomments_benchmark",
    "run_wilds_civilcomments_suite",
    "temporal_benchmark_suite_to_dict",
    "wilds_civilcomments_benchmark_to_dict",
    "wilds_civilcomments_suite_to_dict",
]
